-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/amulet_red_heart.zip"),
}

return CreatePrefabSkin("amulet_red_heart",
{
	base_prefab = "amulet",
	type = "item",
	assets = assets,
	build_name = "amulet_red_heart",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	init_fn = function(inst) amulet_init_fn(inst, "amulet_red_heart") end,
	skin_tags = { "AMULET_RED", "HEART", "CRAFTABLE", },
	release_group = 39,
})
