-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/birdcage_ornamental.zip"),
}

return CreatePrefabSkin("birdcage_ornamental",
{
	base_prefab = "birdcage",
	type = "item",
	assets = assets,
	build_name = "birdcage_ornamental",
	rarity = "Distinguished",
	init_fn = function(inst) birdcage_init_fn(inst, "birdcage_ornamental") end,
	marketable = true,
	release_group = 22,
})
