-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/birdcage_romantic.zip"),
}

return CreatePrefabSkin("birdcage_romantic",
{
	base_prefab = "birdcage",
	type = "item",
	assets = assets,
	build_name = "birdcage_romantic",
	rarity = "Distinguished",
	rarity_modifier = "Seasonal",
	init_fn = function(inst) birdcage_init_fn(inst, "birdcage_romantic") end,
	skin_tags = { "BIRDCAGE", "HEART", "CRAFTABLE", },
	release_group = 39,
})
