-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/featherhat_crown.zip"),
}

return CreatePrefabSkin("featherhat_crown",
{
	base_prefab = "featherhat",
	type = "item",
	assets = assets,
	build_name = "featherhat_crown",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	init_fn = function(inst) featherhat_init_fn(inst, "featherhat_crown") end,
	release_group = 32,
})
