-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/firepit_firebird.zip"),
}

return CreatePrefabSkin("firepit_firebird",
{
	base_prefab = "firepit",
	type = "item",
	assets = assets,
	build_name = "firepit_firebird",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	prefabs = { "firepit_firebird_puff_fx", },
	init_fn = function(inst) firepit_init_fn(inst, "firepit_firebird", Vector3(0, -5, 0)) end,
	skin_tags = { "FIREPIT", "HEART", "CRAFTABLE", },
	fx_prefab = { "firepit_firebird_puff_fx", },
	release_group = 39,
})
