-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/hat_puppy_cap.zip"),
}

return CreatePrefabSkin("hat_puppy_cap",
{
	base_prefab = "catcoonhat",
	type = "item",
	assets = assets,
	build_name = "hat_puppy_cap",
	rarity = "Distinguished",
	rarity_modifier = "Seasonal",
	init_fn = function(inst) catcoonhat_init_fn(inst, "hat_puppy_cap") end,
	skin_tags = { "CATCOONHAT", "VARG", "CRAFTABLE", },
	release_group = 40,
})
