-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_shadow.zip"),
}

return CreatePrefabSkin("wathgrithr_shadow",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_shadow",
	rarity = "Elegant",
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_shadow", },
})
