-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wathgrithr_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wathgrithr_nature.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wathgrithr_nature.xml", 192),
}

return CreatePrefabSkin("wathgrithr_nature",
{
	base_prefab = "wathgrithr",
	type = "base",
	assets = assets,
	build_name = "wathgrithr_nature",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "VARG", "BASE", "CHARACTER", "WATHGRITHR", },
	bigportrait = { build = "bigportraits/wathgrithr_nature.xml", symbol = "wathgrithr_nature_oval.tex"},
	skins = { ghost_skin = "ghost_wathgrithr_build", normal_skin = "wathgrithr_nature", },
	release_group = 40,
})
