-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wendy_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wendy_shadow.zip"),
}

return CreatePrefabSkin("wendy_shadow",
{
	base_prefab = "wendy",
	type = "base",
	assets = assets,
	build_name = "wendy_shadow",
	rarity = "Elegant",
	skins = { ghost_skin = "ghost_wendy_build", normal_skin = "wendy_shadow", },
	torso_untuck_builds = { "wendy_shadow", },
})
