-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wes_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wes_nature.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wes_nature.xml", 192),
}

return CreatePrefabSkin("wes_nature",
{
	base_prefab = "wes",
	type = "base",
	assets = assets,
	build_name = "wes_nature",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "VARG", "BASE", "CHARACTER", "WES", },
	bigportrait = { build = "bigportraits/wes_nature.xml", symbol = "wes_nature_oval.tex"},
	skins = { ghost_skin = "ghost_wes_build", normal_skin = "wes_nature", },
	torso_tuck_builds = { "wes_nature", },
	has_alternate_for_body = { "wes_nature", },
	has_alternate_for_skirt = { "wes_nature", },
	release_group = 40,
})
