-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wickerbottom_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wickerbottom_formal.zip"),
}

return CreatePrefabSkin("wickerbottom_formal",
{
	base_prefab = "wickerbottom",
	type = "base",
	assets = assets,
	build_name = "wickerbottom_formal",
	rarity = "Elegant",
	skins = { ghost_skin = "ghost_wickerbottom_build", normal_skin = "wickerbottom_formal", },
	torso_tuck_builds = { "wickerbottom_formal", },
	has_alternate_for_body = { "wickerbottom_formal", },
	has_alternate_for_skirt = { "wickerbottom_formal", },
	feet_cuff_size = { wickerbottom_formal = 3, },
})
