-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wilson_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wilson_formal.zip"),
}

return CreatePrefabSkin("wilson_formal",
{
	base_prefab = "wilson",
	type = "base",
	assets = assets,
	build_name = "wilson_formal",
	rarity = "Elegant",
	skins = { ghost_skin = "ghost_wilson_build", normal_skin = "wilson_formal", },
})
