-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_combatant.zip"),
}

return CreatePrefabSkin("winona_combatant",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_combatant",
	rarity = "Event",
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_combatant", },
	release_group = 32,
})
