-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_winona_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/winona_nature.zip"),
	Asset("ATLAS_BUILD", "bigportraits/winona_nature.xml", 192),
}

return CreatePrefabSkin("winona_nature",
{
	base_prefab = "winona",
	type = "base",
	assets = assets,
	build_name = "winona_nature",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "VARG", "BASE", "CHARACTER", "WINONA", },
	bigportrait = { build = "bigportraits/winona_nature.xml", symbol = "winona_nature_oval.tex"},
	skins = { ghost_skin = "ghost_winona_build", normal_skin = "winona_nature", },
	release_group = 40,
})
