-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("DYNAMIC_ANIM", "anim/dynamic/winterhat_fancy_puppy.zip"),
}

return CreatePrefabSkin("winterhat_fancy_puppy",
{
	base_prefab = "winterhat",
	type = "item",
	assets = assets,
	build_name = "winterhat_fancy_puppy",
	rarity = "Loyal",
	init_fn = function(inst) winterhat_init_fn(inst, "winterhat_fancy_puppy") end,
	skin_tags = { "WINTERHAT", "VARG", "CRAFTABLE", },
	release_group = 40,
})
