-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_woodie_build.zip"),
	Asset("ANIM", "anim/ghost_werebeaver_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/woodie_nature.zip"),
	Asset("ANIM", "anim/werebeaver_build.zip"),
	Asset("ATLAS_BUILD", "bigportraits/woodie_nature.xml", 192),
}

return CreatePrefabSkin("woodie_nature",
{
	base_prefab = "woodie",
	type = "base",
	assets = assets,
	build_name = "woodie_nature",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "VARG", "BASE", "CHARACTER", "WOODIE", },
	bigportrait = { build = "bigportraits/woodie_nature.xml", symbol = "woodie_nature_oval.tex"},
	skins = { ghost_skin = "ghost_woodie_build", ghost_werebeaver_skin = "ghost_werebeaver_build", normal_skin = "woodie_nature", werebeaver_skin = "werebeaver_build", },
	release_group = 40,
})
