-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_woodie_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/woodie_combatant.zip"),
}

return CreatePrefabSkin("woodie_combatant",
{
	base_prefab = "woodie",
	type = "base",
	assets = assets,
	build_name = "woodie_combatant",
	rarity = "Event",
	skins = { ghost_skin = "ghost_woodie_build", normal_skin = "woodie_combatant", },
	release_group = 32,
})
