-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_woodie_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/woodie_gladiator.zip"),
	Asset("ATLAS_BUILD", "bigportraits/woodie_gladiator.xml", 128),
}

return CreatePrefabSkin("woodie_gladiator",
{
	base_prefab = "woodie",
	type = "base",
	assets = assets,
	build_name = "woodie_gladiator",
	rarity = "Elegant",
	rarity_modifier = "EventModifier",
	skin_tags = { "LAVA", "BASE", "CHARACTER", "WOODIE", },
	bigportrait = { build = "bigportraits/woodie_gladiator.xml", symbol = "woodie_gladiator_oval.tex"},
	skins = { ghost_skin = "ghost_woodie_build", normal_skin = "woodie_gladiator", },
	release_group = 32,
})
