-- AUTOGENERATED CODE BY export_accountitems.lua

local assets =
{
	Asset("ANIM", "anim/ghost_wx78_build.zip"),
	Asset("DYNAMIC_ANIM", "anim/dynamic/wx78_nature.zip"),
	Asset("ATLAS_BUILD", "bigportraits/wx78_nature.xml", 192),
}

return CreatePrefabSkin("wx78_nature",
{
	base_prefab = "wx78",
	type = "base",
	assets = assets,
	build_name = "wx78_nature",
	rarity = "Elegant",
	rarity_modifier = "Seasonal",
	skin_tags = { "VARG", "BASE", "CHARACTER", "WX78", },
	bigportrait = { build = "bigportraits/wx78_nature.xml", symbol = "wx78_nature_oval.tex"},
	skins = { ghost_skin = "ghost_wx78_build", normal_skin = "wx78_nature", },
	feet_cuff_size = { wx78_nature = 3, },
	release_group = 40,
})
