-- AUTOGENERATED CODE BY export_accountitems.lua

CLOTHING =
{
	body_buttons_blue_sky =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_blue_sky",
		torso_tuck = "untucked",
	},
	body_buttons_green_laurel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_green_laurel",
		torso_tuck = "untucked",
	},
	body_buttons_pink_hibiscus =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_pink_hibiscus",
		torso_tuck = "untucked",
	},
	body_buttons_white_ghost =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_white_ghost",
		torso_tuck = "untucked",
	},
	body_flannel_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_blue_snowbird",
		torso_tuck = "untucked",
	},
	body_flannel_orange_lumberjack =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_orange_lumberjack",
		torso_tuck = "untucked",
	},
	body_flannel_purple_grape =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_purple_grape",
		torso_tuck = "untucked",
	},
	body_polo_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_polo_white_marble =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_white_marble",
		torso_tuck = "untucked",
	},
	body_polo_yellow_goldenrod =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_yellow_goldenrod",
		torso_tuck = "untucked",
	},
	body_suspenders_pink_pearl =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_pink_pearl",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_suspenders_white_pure =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_white_pure",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_suspenders_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_yellow_flax",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_blue_snowbird",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_brown_beaver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_brown_beaver",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_grey_silver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_grey_silver",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_red_firehound =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_red_firehound",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_trenchcoat_brown_fawn =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "arm_lower", "skirt", },
		override_build = "body_trenchcoat_brown_fawn",
		torso_tuck = "untucked",
		rarity = "Spiffy",
	},
	body_trenchcoat_yellow_straw =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "arm_lower", "skirt", },
		override_build = "body_trenchcoat_yellow_straw",
		torso_tuck = "untucked",
		rarity = "Spiffy",
	},
	body_trimmed_blouse_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_trimmed_blouse_white_pure =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_white_pure",
		torso_tuck = "untucked",
	},
	body_trimmed_blouse_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_yellow_flax",
		torso_tuck = "untucked",
	},
	body_tshirt_grey_battleship =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_grey_battleship",
		torso_tuck = "untucked",
	},
	body_tshirt_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_tshirt_white_smoke =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_white_smoke",
		torso_tuck = "untucked",
	},
	body_tweedvest_brown_chocolate =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_brown_chocolate",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_green_hunters =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_green_hunters",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_grey_steel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_grey_steel",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_tan_grass =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_tan_grass",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_wathgrithr_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "arm_upper_skin", "skirt", "leg", "foot", },
		override_build = "body_wathgrithr_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_webber_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_webber_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wendy_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", },
		override_build = "body_wendy_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wes_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "body_wes_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wickerbottom_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		override_build = "body_wickerbottom_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_willow_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		override_build = "body_willow_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wilson_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "arm_lower", "leg", },
		symbol_hides = { "skirt", },
		override_build = "body_wilson_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wolfgang_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { arm_upper = "arm_upper_skinny", arm_upper_skin = "arm_upper_skin_skinny", arm_lower = "arm_lower_skinny", },
		symbol_overrides_mighty = { arm_upper = "arm_upper_mighty", torso = "torso_mighty", arm_upper_skin = "arm_upper_skin_mighty", arm_lower = "arm_lower_mighty", },
		symbol_hides = { "skirt", },
		override_build = "body_wolfgang_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_woodie_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "skirt", "leg", },
		override_build = "body_woodie_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wx78_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		override_build = "body_wx78_formal",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	feet_fleece_boot_brown_sepia =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_fleece_boot_brown_sepia",
		rarity = "Classy",
	},
	feet_formal_highheel_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_highheel_white_pure",
		rarity = "Classy",
	},
	feet_formal_lowheel_black_scribble =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_lowheel_black_scribble",
		rarity = "Classy",
	},
	feet_formal_stiletto_black_scribble =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_stiletto_black_scribble",
		rarity = "Classy",
	},
	feet_maryjanes_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_maryjanes_white_pure",
		rarity = "Classy",
	},
	feet_ridingboot_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_ridingboot_white_pure",
		rarity = "Classy",
	},
	hand_beltedgloves_brown_beaver =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_beltedgloves_brown_beaver",
		rarity = "Classy",
	},
	hand_drivergloves_white_ivory =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_drivergloves_white_ivory",
		rarity = "Classy",
	},
	hand_longgloves_grey_battleship =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_grey_battleship",
	},
	hand_longgloves_yellow_straw =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_yellow_straw",
	},
	hand_shortgloves_black_scribble =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_black_scribble",
	},
	hand_shortgloves_red_higgsbury =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_red_higgsbury",
	},
	hand_shortgloves_white_smoke =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_white_smoke",
	},
	hand_wilson_formal =
	{
		type = "hand",
		symbol_overrides = { "hand", "arm_lower_cuff", },
		override_build = "hand_wilson_formal",
		rarity = "Classy",
	},
	legs_checkered_pleats_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_checkered_pleats_blue_cornflower",
		rarity = "Classy",
	},
	legs_checkered_pleats_green_laurel =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_checkered_pleats_green_laurel",
		rarity = "Classy",
	},
	legs_pants_basic_black_scribble =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_black_scribble",
	},
	legs_pants_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_brown_sepia",
	},
	legs_pants_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_grey_dark",
	},
	legs_pants_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_tan_cream",
	},
	legs_skirt_basic_black_scribble =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_black_scribble",
	},
	legs_skirt_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_brown_sepia",
	},
	legs_skirt_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_grey_dark",
	},
	legs_skirt_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_tan_cream",
	},
	legs_skirt_plaid_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_plaid_blue_cornflower",
		rarity = "Classy",
	},
	legs_skirt_plaid_green_pistachio =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_plaid_green_pistachio",
		rarity = "Classy",
	},
}

CLOTHING_SYMBOLS = {}
HIDE_SYMBOLS = {}
for _,v in pairs(CLOTHING) do
	for _,sym in pairs(v.symbol_overrides) do
		table.insert( CLOTHING_SYMBOLS, sym )
	end
	if v.symbol_hides then
		for _,sym in pairs(v.symbol_hides) do
			table.insert( HIDE_SYMBOLS, sym )
		end
	end
end