-- AUTOGENERATED CODE BY export_accountitems.lua
BASE_TORSO_TUCK =
{
	wolfgang = true,
	wolfgang_skinny = true,
	wolfgang_mighty = true,
	wes = true,
	webber = true,
	wickerbottom = true,
}

CLOTHING =
{
	body_buttons_blue_sky =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_blue_sky",
		torso_tuck = false,
	},
	body_buttons_green_laurel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_green_laurel",
		torso_tuck = false,
	},
	body_buttons_pink_hibiscus =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_pink_hibiscus",
		torso_tuck = false,
	},
	body_buttons_white_ghost =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_white_ghost",
		torso_tuck = false,
	},
	body_flannel_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_blue_snowbird",
		torso_tuck = false,
	},
	body_flannel_orange_lumberjack =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_orange_lumberjack",
		torso_tuck = false,
	},
	body_flannel_purple_grape =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_purple_grape",
		torso_tuck = false,
	},
	body_polo_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_red_higgsbury",
		torso_tuck = false,
	},
	body_polo_white_marble =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_white_marble",
		torso_tuck = false,
	},
	body_polo_yellow_goldenrod =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_yellow_goldenrod",
		torso_tuck = false,
	},
	body_suspenders_pink_pearl =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_pink_pearl",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_suspenders_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_yellow_flax",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_sweatervest_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_blue_snowbird",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_sweatervest_brown_beaver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_brown_beaver",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_sweatervest_grey_silver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_grey_silver",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_sweatervest_red_firehound =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_red_firehound",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_trimmed_blouse_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_red_higgsbury",
		torso_tuck = false,
	},
	body_trimmed_blouse_white_pure =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_white_pure",
		torso_tuck = false,
	},
	body_trimmed_blouse_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_yellow_flax",
		torso_tuck = false,
	},
	body_tshirt_grey_battleship =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_grey_battleship",
		torso_tuck = false,
	},
	body_tshirt_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_red_higgsbury",
		torso_tuck = false,
	},
	body_tshirt_white_smoke =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_white_smoke",
		torso_tuck = false,
	},
	body_tweedvest_brown_chocolate =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_brown_chocolate",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_tweedvest_green_hunters =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_green_hunters",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_tweedvest_grey_steel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_grey_steel",
		torso_tuck = false,
		rarity = "Classy",
	},
	body_tweedvest_tan_grass =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_tan_grass",
		torso_tuck = false,
		rarity = "Classy",
	},
	hand_longgloves_grey_battleship =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_grey_battleship",
	},
	hand_longgloves_yellow_straw =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_yellow_straw",
	},
	hand_shortgloves_black_scribble =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_black_scribble",
	},
	hand_shortgloves_red_higgsbury =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_red_higgsbury",
	},
	hand_shortgloves_white_smoke =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_white_smoke",
	},
	legs_checkered_pleats_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_checkered_pleats_blue_cornflower",
		rarity = "Classy",
	},
	legs_pants_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_brown_sepia",
	},
	legs_pants_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_grey_dark",
	},
	legs_pants_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_tan_cream",
	},
	legs_skirt_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		symbol_hides = { "torso_pelvis", },
		override_build = "legs_skirt_basic_brown_sepia",
	},
	legs_skirt_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		symbol_hides = { "torso_pelvis", },
		override_build = "legs_skirt_basic_grey_dark",
	},
	legs_skirt_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		symbol_hides = { "torso_pelvis", },
		override_build = "legs_skirt_basic_tan_cream",
	},
	legs_skirt_plaid_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		symbol_hides = { "torso_pelvis", },
		override_build = "legs_skirt_plaid_blue_cornflower",
		rarity = "Classy",
	},
}

CLOTHING_SYMBOLS = {}
HIDE_SYMBOLS = {}
for _,v in pairs(CLOTHING) do
	for _,sym in pairs(v.symbol_overrides) do
		table.insert( CLOTHING_SYMBOLS, sym )
	end
	if v.symbol_hides then
		for _,sym in pairs(v.symbol_hides) do
			table.insert( HIDE_SYMBOLS, sym )
		end
	end
end