-- AUTOGENERATED CODE BY export_accountitems.lua

CLOTHING =
{
	body_buttons_black_jet =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_black_jet",
		torso_tuck = "untucked",
	},
	body_buttons_blue_sky =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_blue_sky",
		torso_tuck = "untucked",
	},
	body_buttons_green_laurel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_green_laurel",
		torso_tuck = "untucked",
	},
	body_buttons_pink_hibiscus =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_pink_hibiscus",
		torso_tuck = "untucked",
	},
	body_buttons_white_ghost =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_buttons_white_ghost",
		torso_tuck = "untucked",
	},
	body_cardigan_black_jet =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		override_build = "body_cardigan_black_jet",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_cardigan_red_cardinal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		override_build = "body_cardigan_red_cardinal",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_cardigan_teal_jade =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		override_build = "body_cardigan_teal_jade",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_cardigan_white_ghost =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", },
		override_build = "body_cardigan_white_ghost",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_flannel_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_blue_snowbird",
		torso_tuck = "untucked",
	},
	body_flannel_green_napier =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_green_napier",
		torso_tuck = "untucked",
	},
	body_flannel_orange_lumberjack =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_orange_lumberjack",
		torso_tuck = "untucked",
	},
	body_flannel_purple_grape =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_flannel_purple_grape",
		torso_tuck = "untucked",
	},
	body_overalls_black_scribble =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "torso_pelvis", "leg", },
		override_build = "body_overalls_black_scribble",
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
	},
	body_overalls_blue_denim =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "torso_pelvis", "leg", },
		override_build = "body_overalls_blue_denim",
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
	},
	body_overalls_navy_ocean =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "torso_pelvis", "leg", },
		override_build = "body_overalls_navy_ocean",
		torso_tuck = "untucked",
		rarity = "Spiffy",
		legs_cuff_size = 2,
	},
	body_pj_purple_mauve =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "arm_lower_cuff", },
		override_build = "body_pj_purple_mauve",
		torso_tuck = "untucked",
		rarity = "Spiffy",
	},
	body_polo_blue_denim =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_blue_denim",
		torso_tuck = "untucked",
	},
	body_polo_orange_salmon =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_orange_salmon",
		torso_tuck = "untucked",
	},
	body_polo_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_polo_white_marble =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_white_marble",
		torso_tuck = "untucked",
	},
	body_polo_yellow_goldenrod =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_polo_yellow_goldenrod",
		torso_tuck = "untucked",
	},
	body_silk_eveningrobe_blue_frost =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		override_build = "body_silk_eveningrobe_blue_frost",
		torso_tuck = "skirt",
		rarity = "Spiffy",
	},
	body_silk_eveningrobe_pink_ewecus =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		override_build = "body_silk_eveningrobe_pink_ewecus",
		torso_tuck = "skirt",
		rarity = "Spiffy",
	},
	body_silk_eveningrobe_red_rump =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		override_build = "body_silk_eveningrobe_red_rump",
		torso_tuck = "skirt",
		rarity = "Spiffy",
	},
	body_silk_eveningrobe_yellow_goldenrod =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", },
		override_build = "body_silk_eveningrobe_yellow_goldenrod",
		torso_tuck = "skirt",
		rarity = "Spiffy",
	},
	body_silk_loungewear_black_davys =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		override_build = "body_silk_loungewear_black_davys",
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
	},
	body_silk_loungewear_green_laurel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		override_build = "body_silk_loungewear_green_laurel",
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
	},
	body_silk_loungewear_red_cranberry =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		override_build = "body_silk_loungewear_red_cranberry",
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
	},
	body_silk_loungewear_white_marble =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "skirt", "torso_pelvis", "leg", },
		override_build = "body_silk_loungewear_white_marble",
		torso_tuck = "skirt",
		rarity = "Distinguished",
		legs_cuff_size = 5,
	},
	body_sleepgown_blue_ice =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		override_build = "body_sleepgown_blue_ice",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_suspenders_pink_pearl =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_pink_pearl",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_suspenders_white_pure =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_white_pure",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_suspenders_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_suspenders_yellow_flax",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_blue_snowbird =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_blue_snowbird",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_brown_beaver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_brown_beaver",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_green_forest =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_green_forest",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_grey_silver =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_grey_silver",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_sweatervest_red_firehound =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_sweatervest_red_firehound",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_trenchcoat_brown_fawn =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "arm_lower", "skirt", },
		override_build = "body_trenchcoat_brown_fawn",
		torso_tuck = "untucked",
		rarity = "Spiffy",
	},
	body_trenchcoat_yellow_straw =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", "arm_lower", "skirt", },
		override_build = "body_trenchcoat_yellow_straw",
		torso_tuck = "untucked",
		rarity = "Spiffy",
	},
	body_trimmed_blouse_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_trimmed_blouse_white_pure =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_white_pure",
		torso_tuck = "untucked",
	},
	body_trimmed_blouse_yellow_flax =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_trimmed_blouse_yellow_flax",
		torso_tuck = "untucked",
	},
	body_tshirt_grey_battleship =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_grey_battleship",
		torso_tuck = "untucked",
	},
	body_tshirt_purple_mauve =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_purple_mauve",
		torso_tuck = "untucked",
	},
	body_tshirt_red_higgsbury =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_red_higgsbury",
		torso_tuck = "untucked",
	},
	body_tshirt_white_smoke =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tshirt_white_smoke",
		torso_tuck = "untucked",
	},
	body_tweedvest_blue_lightning =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_blue_lightning",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_brown_chocolate =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_brown_chocolate",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_green_hunters =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_green_hunters",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_grey_steel =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_grey_steel",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_tweedvest_tan_grass =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_tweedvest_tan_grass",
		torso_tuck = "untucked",
		rarity = "Classy",
	},
	body_wathgrithr_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "arm_upper_skin", "skirt", "leg", "foot", },
		override_build = "body_wathgrithr_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wathgrithr_shadow =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "arm_upper_skin", "skirt", "torso_pelvis", "leg", "foot", "arm_lower", "hand", },
		override_build = "body_wathgrithr_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wathgrithr_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "leg", "foot", },
		override_build = "body_wathgrithr_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_waxwell_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "body_waxwell_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_waxwell_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		override_build = "body_waxwell_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_waxwell_unshadow =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		override_build = "body_waxwell_unshadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_webber_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_upper_skin", },
		override_build = "body_webber_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_webber_shadow =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", },
		symbol_hides = { "skirt", "arm_upper", },
		override_build = "body_webber_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_webber_survivor =
	{
		type = "body",
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		override_build = "body_webber_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wendy_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", },
		override_build = "body_wendy_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wendy_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_lower", "arm_upper", "arm_upper_skin", "foot", "hand", "leg", "skirt", "torso", "torso_pelvis", },
		override_build = "body_wendy_shadow",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	body_wendy_survivor =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "foot", },
		override_build = "body_wendy_survivor",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	body_wes_formal =
	{
		type = "body",
		symbol_overrides = { "torso", "arm_upper", "arm_lower", "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "body_wes_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wes_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_lower", "arm_upper_skin", "foot", "hand", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", "arm_upper", },
		override_build = "body_wes_shadow",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wes_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", "arm_upper", },
		override_build = "body_wes_survivor",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wickerbottom_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		override_build = "body_wickerbottom_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wickerbottom_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "arm_upper_skin", "foot", "leg", "skirt", "torso", "torso_pelvis", },
		override_build = "body_wickerbottom_shadow",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_wickerbottom_survivor =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", "leg", "foot", },
		override_build = "body_wickerbottom_survivor",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_willow_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "skirt", },
		override_build = "body_willow_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_willow_shadow =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "leg", "skirt", "foot", },
		override_build = "body_willow_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_willow_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "arm_upper", "skirt", },
		override_build = "body_willow_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wilson_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", "arm_lower", "leg", },
		symbol_hides = { "skirt", },
		override_build = "body_wilson_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wilson_shadow =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "leg", "arm_upper", "arm_upper_skin", "arm_lower", "foot", },
		symbol_hides = { "skirt", },
		override_build = "body_wilson_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wilson_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "leg", "arm_upper", "arm_upper_skin", "foot", },
		symbol_hides = { "skirt", },
		override_build = "body_wilson_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wolfgang_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { arm_upper = "arm_upper_skinny", arm_upper_skin = "arm_upper_skin_skinny", arm_lower = "arm_lower_skinny", },
		symbol_overrides_mighty = { arm_upper = "arm_upper_mighty", torso = "torso_mighty", arm_upper_skin = "arm_upper_skin_mighty", arm_lower = "arm_lower_mighty", },
		symbol_hides = { "skirt", },
		override_build = "body_wolfgang_formal",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wolfgang_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_lower_cuff", "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { torso_pelvis = "torso_pelvis_skinny", torso = "torso_skinny", },
		symbol_overrides_mighty = { torso_pelvis = "torso_pelvis_mighty", torso = "torso_mighty", },
		symbol_hides = { "skirt", "arm_upper", },
		override_build = "body_wolfgang_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wolfgang_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_overrides_skinny = { },
		symbol_overrides_mighty = { torso_pelvis = "torso_pelvis_mighty", torso = "torso_mighty", },
		symbol_hides = { "skirt", },
		override_build = "body_wolfgang_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
		legs_cuff_size = 2,
	},
	body_woodie_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "arm_upper_skin", "arm_lower", "torso", "torso_pelvis", "skirt", "leg", },
		override_build = "body_woodie_formal",
		torso_tuck = "full",
		rarity = "Distinguished",
	},
	body_woodie_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_lower", "arm_lower_cuff", "arm_upper", "arm_upper_skin", "foot", "leg", "torso", "torso_pelvis", },
		symbol_hides = { "skirt", },
		override_build = "body_woodie_shadow",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_woodie_survivor =
	{
		type = "body",
		symbol_overrides = { "torso", "torso_pelvis", "leg", "foot", },
		symbol_hides = { "skirt", },
		override_build = "body_woodie_survivor",
		torso_tuck = "untucked",
		rarity = "Distinguished",
	},
	body_wx78_formal =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		override_build = "body_wx78_formal",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	body_wx78_shadow =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		override_build = "body_wx78_shadow",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	body_wx78_survivor =
	{
		type = "body",
		symbol_overrides = { "arm_upper", "torso", "torso_pelvis", },
		override_build = "body_wx78_survivor",
		torso_tuck = "skirt",
		rarity = "Distinguished",
	},
	feet_bootie_black_scribble =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_bootie_black_scribble",
	},
	feet_bunnyslippers_purple_mauve =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_bunnyslippers_purple_mauve",
		rarity = "Distinguished",
		feet_cuff_size = 3,
	},
	feet_fleece_boot_brown_sepia =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_fleece_boot_brown_sepia",
		rarity = "Classy",
		feet_cuff_size = 5,
	},
	feet_formal_highheel_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_highheel_white_pure",
		rarity = "Classy",
		feet_cuff_size = 5,
	},
	feet_formal_lowheel_black_scribble =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_lowheel_black_scribble",
		rarity = "Classy",
	},
	feet_formal_stiletto_black_scribble =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_formal_stiletto_black_scribble",
		rarity = "Classy",
	},
	feet_fuzzyslippers_blue_ice =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_fuzzyslippers_blue_ice",
		rarity = "Distinguished",
		feet_cuff_size = 5,
	},
	feet_maryjanes_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_maryjanes_white_pure",
		rarity = "Classy",
	},
	feet_ridingboot_white_pure =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_ridingboot_white_pure",
		rarity = "Classy",
		feet_cuff_size = 10,
	},
	feet_sneakers_blue_catcoon =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_sneakers_blue_catcoon",
	},
	feet_sneakers_green_cactus =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_sneakers_green_cactus",
	},
	feet_sneakers_orange_carrot =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_sneakers_orange_carrot",
	},
	feet_sneakers_red_auburn =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_sneakers_red_auburn",
	},
	feet_workboot_brown_chocolate =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_workboot_brown_chocolate",
		rarity = "Classy",
		feet_cuff_size = 5,
	},
	feet_workboot_tan_clay =
	{
		type = "feet",
		symbol_overrides = { "foot", },
		override_build = "feet_workboot_tan_clay",
		rarity = "Classy",
		feet_cuff_size = 5,
	},
	hand_beltedgloves_brown_beaver =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_beltedgloves_brown_beaver",
		rarity = "Classy",
	},
	hand_beltedgloves_red_firehound =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_beltedgloves_red_firehound",
		rarity = "Classy",
	},
	hand_beltedgloves_teal_jungle =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_beltedgloves_teal_jungle",
		rarity = "Classy",
	},
	hand_drivergloves_white_ivory =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_drivergloves_white_ivory",
		rarity = "Classy",
	},
	hand_longgloves_green_hunters =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_green_hunters",
	},
	hand_longgloves_grey_battleship =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_grey_battleship",
	},
	hand_longgloves_white_pure =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_white_pure",
	},
	hand_longgloves_yellow_straw =
	{
		type = "hand",
		symbol_overrides = { "arm_lower_cuff", "hand", },
		override_build = "hand_longgloves_yellow_straw",
	},
	hand_shortgloves_black_scribble =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_black_scribble",
	},
	hand_shortgloves_blue_cornflower =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_blue_cornflower",
	},
	hand_shortgloves_red_higgsbury =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_red_higgsbury",
	},
	hand_shortgloves_white_smoke =
	{
		type = "hand",
		symbol_overrides = { "hand", },
		override_build = "hand_shortgloves_white_smoke",
	},
	hand_waxwell_formal =
	{
		type = "hand",
		symbol_overrides = { "hand", "arm_lower_cuff", },
		override_build = "hand_waxwell_formal",
		rarity = "Classy",
	},
	hand_wilson_formal =
	{
		type = "hand",
		symbol_overrides = { "hand", "arm_lower_cuff", },
		override_build = "hand_wilson_formal",
		rarity = "Classy",
	},
	legs_checkered_pleats_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_checkered_pleats_blue_cornflower",
		rarity = "Classy",
		legs_cuff_size = 2,
	},
	legs_checkered_pleats_green_laurel =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_checkered_pleats_green_laurel",
		rarity = "Classy",
		legs_cuff_size = 2,
	},
	legs_pants_basic_black_scribble =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_black_scribble",
		legs_cuff_size = 2,
	},
	legs_pants_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_brown_sepia",
		legs_cuff_size = 2,
	},
	legs_pants_basic_green_forest =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_green_forest",
		legs_cuff_size = 2,
	},
	legs_pants_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_grey_dark",
		legs_cuff_size = 2,
	},
	legs_pants_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pants_basic_tan_cream",
		legs_cuff_size = 2,
	},
	legs_pj_purple_mauve =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_pj_purple_mauve",
		rarity = "Spiffy",
		legs_cuff_size = 2,
	},
	legs_skirt_basic_black_scribble =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_black_scribble",
	},
	legs_skirt_basic_brown_sepia =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_brown_sepia",
	},
	legs_skirt_basic_grey_dark =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_grey_dark",
	},
	legs_skirt_basic_pink_pigman =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_pink_pigman",
	},
	legs_skirt_basic_tan_cream =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_basic_tan_cream",
	},
	legs_skirt_plaid_blue_cornflower =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_plaid_blue_cornflower",
		rarity = "Classy",
	},
	legs_skirt_plaid_green_pistachio =
	{
		type = "legs",
		symbol_overrides = { "skirt", },
		override_build = "legs_skirt_plaid_green_pistachio",
		rarity = "Classy",
	},
	legs_tweed_knickerbocker_green_hunters =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_tweed_knickerbocker_green_hunters",
		rarity = "Classy",
	},
	legs_tweed_knickerbocker_tan_grass =
	{
		type = "legs",
		symbol_overrides = { "torso_pelvis", "leg", },
		symbol_hides = { "skirt", },
		override_build = "legs_tweed_knickerbocker_tan_grass",
		rarity = "Classy",
	},
}

CLOTHING_SYMBOLS = {}
HIDE_SYMBOLS = {}
for _,v in pairs(CLOTHING) do
	for _,sym in pairs(v.symbol_overrides) do
		table.insert( CLOTHING_SYMBOLS, sym )
	end
	if v.symbol_hides then
		for _,sym in pairs(v.symbol_hides) do
			table.insert( HIDE_SYMBOLS, sym )
		end
	end
end