-- AUTOGENERATED CODE BY export_accountitems.lua

EMOTE_ITEMS =
{
	emote_sleepy =
	{
		rarity = "Reward",
		cmd_name = "sleepy",
		type = "emote",
		skin_tags = { "EMOTE", },
		data =
		{
			item_type = "emote_sleepy",
			requires_validation = true,
			anim = "emote_sleepy",
			fx = false,
			loop = false,
			mounted = true,
			mountsound = "curious",
			mountsounddelay = 0.88,
			sounddelay = 0.26666666666667,
			soundoverride = "eye_rub_vo",
		},
		aliases =
		{
			"eyerub",
		},
		release_group = 20,
	},
	emote_swoon =
	{
		rarity = "Loyal",
		cmd_name = "swoon",
		type = "emote",
		skin_tags = { "EMOTE", },
		data =
		{
			item_type = "emote_swoon",
			requires_validation = true,
			anim = "emote_swoon",
			fx = false,
			loop = false,
			mounted = true,
			mountsound = "curious",
		},
		release_group = 24,
	},
	emote_yawn =
	{
		rarity = "Reward",
		cmd_name = "yawn",
		type = "emote",
		skin_tags = { "EMOTE", },
		data =
		{
			item_type = "emote_yawn",
			requires_validation = true,
			anim = "emote_yawn",
			fx = false,
			loop = false,
			mounted = true,
			mountsound = "yell",
			mountsounddelay = 0.1,
			sounddelay = 0.5,
			soundoverride = "yawn",
		},
		release_group = 20,
	},
}

