-- AUTOGENERATED CODE BY export_accountitems.lua

PREFAB_SKINS = {
	backpack = 
	{
		"backpack_beefalo",
		"backpack_buckle_grey_pewter",
		"backpack_buckle_navy_phthalo",
		"backpack_buckle_red_rook",
		"backpack_camping_green_viridian",
		"backpack_camping_orange_carrot",
		"backpack_camping_red_koalefant",
		"backpack_mushy",
		"backpack_poop",
		"backpack_rabbit",
		"backpack_smallbird",
		"backpack_spider",
	},
	wathgrithr = 
	{
		"wathgrithr_none",
	},
	webber = 
	{
		"webber_none",
	},
	wendy = 
	{
		"wendy_none",
	},
	wes = 
	{
		"wes_none",
	},
	wickerbottom = 
	{
		"wickerbottom_none",
	},
	willow = 
	{
		"willow_none",
	},
	wilson = 
	{
		"wilson_none",
	},
	wolfgang = 
	{
		"wolfgang_none",
	},
	woodie = 
	{
		"woodie_none",
	},
	wx78 = 
	{
		"wx78_none",
	},

}

PREFAB_SKINS_IDS = {}
for prefab,skins in pairs(PREFAB_SKINS) do
	PREFAB_SKINS_IDS[prefab] = {}
	for k,v in pairs(skins) do
		PREFAB_SKINS_IDS[prefab][v] = k
	end
end
